apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-mongodb
  name: database-mongodb
spec:
  containers:
  - image: mongo
    name: database-mongodb
    ports:
    - containerPort: 27017
    resources:
      limits:
        cpu: 500m
        memory: "536870912"
      requests:
        cpu: "1"
        memory: "268435456"
    volumeMounts:
    - mountPath: /data/db
      name: database-mongodb-claim0
  restartPolicy: OnFailure
  volumes:
  - name: database-mongodb-claim0
    persistentVolumeClaim:
      claimName: database-mongodb-claim0
status: {}
